//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoEcoleEntities : DbContext
    {
        public autoEcoleEntities()
            : base("name=autoEcoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Paiement> Paiements { get; set; }
        public DbSet<Participan_typePermi> Participan_typePermi { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<typePermi> typePermis { get; set; }
        public DbSet<user> users { get; set; }
    }
}
