//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int numBon { get; set; }
        public Nullable<int> numP { get; set; }
        public decimal prixPaye { get; set; }
        public System.DateTime date_ { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
