//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.Paiements = new HashSet<Paiement>();
            this.Participan_typePermi = new HashSet<Participan_typePermi>();
        }
    
        public int numP { get; set; }
        public string nomP { get; set; }
        public string cin { get; set; }
        public string phone { get; set; }
        public decimal prix { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
    
        public virtual ICollection<Paiement> Paiements { get; set; }
        public virtual ICollection<Participan_typePermi> Participan_typePermi { get; set; }
    }
}
