//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participan_typePermi
    {
        public int idParType { get; set; }
        public string typePermi { get; set; }
        public Nullable<int> participant { get; set; }
    
        public virtual Participant Participant1 { get; set; }
        public virtual typePermi typePermi1 { get; set; }
    }
}
