//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Collections.Generic;
    
    public partial class typePermi
    {
        public typePermi()
        {
            this.Participan_typePermi = new HashSet<Participan_typePermi>();
        }
    
        public string type_permi { get; set; }
    
        public virtual ICollection<Participan_typePermi> Participan_typePermi { get; set; }
    }
}
